export const PRIMARY_BLUE = '#2B3B65';
export const PRIMARY_TEXT = '#303030';
export const PRIMARY_RED = '#B31717';
export const GREY = '#DBDBDB';
export const SECONDARY_ORANGE = '#E38A3E';
export const SECONDARY_RED = '#981212';
export const LIGHT_GREY = '#FAFAFA';
export const SECONDARY_BLUE = '#1D5893';
export const TOP_BLUE ='#4a7bb7';
