version: '2.1'

services:
  oclmsp:
    image: openconceptlab/oclmsp:${ENVIRONMENT-dev}
    build:
      context: .
    environment:
    - OCL_DOMAIN=${OCL_DOMAIN:-staging.openconceptlab.org}
    - ENVIRONMENT=${ENVIRONMENT:-dev}
    - MSP_PORT=80
    ports:
    - 80:80
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "-s", "http://localhost/"]
